name: OpenAPI SDK Generator

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - main

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, java]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install OpenAPI Generator
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.14.0/openapi-generator-cli-7.14.0.jar -O openapi-generator-cli.jar
          echo "OpenAPI Generator installed."

      - name: Generate SDKs
        run: |
          java -jar openapi-generator-cli.jar generate \
            -i ./openapi.yaml \  # Path to your OpenAPI spec file
            -g ${{ matrix.language }} \         # Language for SDK generation
            -o ./generated-sdk/${{ matrix.language }}  # Output directory for the generated SDK

      - name: Create Release
        id: create_release
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "Creating release version: $VERSION"
          gh release create "v$VERSION" ./generated-sdk/* --title "SDK Release $VERSION" --notes "Generated SDKs for multiple languages."
